services:
  site:
    container_name: drago-site
    build:
      context: ./site/
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - drago-network
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    container_name: drago-api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - drago-network
    ports:
      - "8088:8088"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  drago-network:
    driver: bridge
