name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: amd64
            target: x86_64-unknown-linux-musl
            runner: ubuntu-latest
          - arch: arm64
            target: aarch64-unknown-linux-musl
            runner: ubuntu-latest

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          working-directory: ./client

      - name: Install zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0

      - name: Install cargo-zigbuild
        run: cargo install cargo-zigbuild

      - name: Build static binary
        working-directory: ./client
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
          DRAGO_API_URL: "https://api.dragodns.com"
        run: |
          cargo zigbuild --release --target ${{ matrix.target }}
      - name: Package
        run: |
          tar czf drago-${{ matrix.arch }}.tar.gz \
            -C client/target/${{ matrix.target }}/release drago
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: drago-${{ matrix.arch }}.tar.gz
